### ISSUE TITLE
tested with a big json (170k+ lines) and it not count elements on array, it can be fixed?

### ISSUE THREAD

**Issue by fabian-silva** [R35007/data-size-count-vscode-extension#1]

**Comment by R35007** [comment]
Thanks for the handsup.  I will try to fix it.  😊

**Comment by R35007** [comment]
vs code cant able to read the files that are more than 4mb. I believe this has been fixed in upcoming vs code versions. can you please try it now

**Comment by R35007** [comment]
Fixed Now :)
