### ISSUE TITLE
Display arrays length with CodeLens

### ISSUE THREAD

**Issue by Delapouite** [R35007/data-size-count-vscode-extension#2]
Hi

Thanks a lot for this extension.
Currently, the information is displayed in the statusBar, which is nice because it's non intrusive.

But sometimes you need the same info more clearly visible, right in the middle in the editor. I reckon it would be great if a CodeLens could be added above arrays in JavaScript and TypeScript to display their length.

As a recap, here's what a CodeLens feels like when used for other purposes.

![image](https://user-images.githubusercontent.com/39315/226304656-8ac2ee71-e2a5-4637-b78d-0ea5c7d72100.png)

Thanks!

**Comment by R35007** [comment]
Hi,

I am glad that this extension is useful for you.

Right now this extension works on demand. Means it gets the array or object
size or length only on selection and not on page load.

To get the Code lense it must be triggered on page load and this extension
can't be done on page load.

Still it's a good thought and will consider the  suggestion. I will check
what I can do for that.

Thanks,
Siva
